FROM python:latest

RUN pip3 install flask

RUN pip3 install requests

RUN pip3 install psycopg2

WORKDIR /home/mail_app

COPY src/createDB.py src/postgres.py src/auth_server.py src/database.ini src/config.py src/authentication.py /home/mail_app/
RUN ls -la && pwd
EXPOSE 5000/tcp


CMD ["sh","-c","python3 createDB.py && python3 auth_server.py" ]
#RUN python3 mail_app.py
